// actionTypes.js
export const ADD_ACCOUNT_REQUEST_SUCCESS = 'ADD_ACCOUNT_REQUEST_SUCCESS';
export const ADD_ACCOUNT_REQUEST_FAILURE = 'ADD_ACCOUNT_REQUEST_FAILURE';
export const UPDATE_ACCOUNT_REQUEST_SUCCESS = 'UPDATE_ACCOUNT_REQUEST_SUCCESS';
export const UPDATE_ACCOUNT_REQUEST_FAILURE = 'UPDATE_ACCOUNT_REQUEST_FAILURE';
export const FETCH_ALL_ACCOUNT_REQUESTS_SUCCESS = 'FETCH_ALL_ACCOUNT_REQUESTS_SUCCESS';
export const FETCH_ALL_ACCOUNT_REQUESTS_FAILURE = 'FETCH_ALL_ACCOUNT_REQUESTS_FAILURE';
export const FETCH_SINGLE_ACCOUNT_REQUEST_SUCCESS = 'FETCH_SINGLE_ACCOUNT_REQUEST_SUCCESS';
export const FETCH_SINGLE_ACCOUNT_REQUEST_FAILURE = 'FETCH_SINGLE_ACCOUNT_REQUEST_FAILURE';
export const DELETE_ACCOUNT_REQUEST_SUCCESS = 'DELETE_ACCOUNT_REQUEST_SUCCESS';
export const DELETE_ACCOUNT_REQUEST_FAILURE = 'DELETE_ACCOUNT_REQUEST_FAILURE';
